defmodule AgentFabricOrchestrator.FabricClient do
  @moduledoc """
  Elixir client for the Agent Fabric TypeScript daemon Unix domain socket protocol.

  Communicates with the daemon using the JSON-line protocol:

    - Connect to the UDS socket
    - Send one JSON line
    - Receive one JSON line
    - Disconnect

  Each request includes a unique string id for correlation.  The daemon
  response is `{"id":"...","ok":true,"result":{...}}` on success or
  `{"id":"...","ok":false,"error":{"code":"...","message":"...","retryable":bool}}`
  on failure.

  ## Protocol Reference

  The TypeScript daemon accepts two top-level message types:

    - `register` --- `{"id":"...","type":"register","payload":BridgeRegister}`
    - `call`     --- `{"id":"...","type":"call","tool":"...","input":{...},"context":CallContext}`

  ## Transport Abstraction

  The `request/2` function accepts an optional third argument `:transport`, a
  `(encoded_json_line -> {:ok, decoded_map} | {:error, reason})` function.
  When omitted, a real UDS connection is used. This makes the module fully
  testable against a fake socket.

  ## Configurable Defaults

    - `default_socket_path/0` --- `~/.agent-fabric/agent.sock`
    - `default_register_payload/0` --- sensible defaults for Elixir orchestrator
  """

  defmodule Session do
    @moduledoc "Registered bridge session."
    defstruct [:session_id, :session_token, :origin_peer_id, :expires_at, warnings: []]
  end

  @type session :: %Session{}

  @typedoc "Transport function: receives JSON-line string, returns decoded response map or error"
  @type transport :: (String.t() -> {:ok, map()} | {:error, term()})

  @doc """
  Register an Elixir bridge session with the daemon.

  Accepts an optional `transport` callback. When omitted, a real UDS
  connection is opened at `socket_path`.

  Returns `{:ok, %Session{}}` or `{:error, reason}`.
  """
  @spec register(Path.t(), map(), keyword()) :: {:ok, session()} | {:error, term()}
  def register(
        socket_path \\ default_socket_path(),
        payload \\ default_register_payload(),
        opts \\ []
      ) do
    case request(socket_path, %{id: unique_id(), type: "register", payload: payload}, opts) do
      {:ok, response} ->
        {:ok,
         %Session{
           session_id: response["sessionId"],
           session_token: response["sessionToken"],
           origin_peer_id: response["originPeerId"],
           expires_at: response["expiresAt"],
           warnings: response["warnings"] || []
         }}

      {:error, reason} ->
        {:error, reason}
    end
  end

  @doc """
  Call one Agent Fabric tool.

  Accepts an `opts` keyword list:
    - `:workspace_root` --- override `context.workspaceRoot`
    - `:idempotency_key` --- override `context.idempotencyKey` (auto-generated by default)
    - `:context` --- additional context fields merged last
    - `:transport` --- inject a fake transport function for testing
  """
  @spec call(Path.t(), session(), String.t(), map(), keyword()) :: {:ok, map()} | {:error, term()}
  def call(socket_path \\ default_socket_path(), %Session{} = session, tool, input, opts \\ []) do
    context =
      %{
        sessionId: session.session_id,
        sessionToken: session.session_token,
        workspaceRoot: opts[:workspace_root] || File.cwd!(),
        idempotencyKey: opts[:idempotency_key] || unique_id()
      }
      |> Map.merge(Map.new(opts[:context] || []))

    request(
      socket_path,
      %{
        id: unique_id(),
        type: "call",
        tool: tool,
        input: input,
        context: context
      },
      opts
    )
  end

  @doc """
  Close the current bridge session.

  Convenience wrapper around `call/5` with `"fabric_session_close"`.
  """
  @spec close_session(Path.t(), session(), keyword()) :: {:ok, map()} | {:error, term()}
  def close_session(socket_path \\ default_socket_path(), %Session{} = session, opts \\ []) do
    call(socket_path, session, "fabric_session_close", %{}, opts)
  end

  @doc """
  Send a raw JSON-line request.

  When `opts[:transport]` is a 1-arity function, it is called with the
  encoded JSON line and must return `{:ok, decoded_map}` or
  `{:error, reason}`.  Otherwise a real UDS connection is opened.
  """
  @spec request(Path.t(), map(), keyword()) :: {:ok, map()} | {:error, term()}
  def request(socket_path, request, opts \\ []) do
    encoded = Jason.encode!(request) <> "\n"

    transport_fn = opts[:transport]

    if is_function(transport_fn, 1) do
      case transport_fn.(encoded) do
        {:ok, response} -> decode_response_struct(response)
        {:error, reason} -> {:error, reason}
      end
    else
      with {:ok, socket} <-
             :gen_tcp.connect({:local, String.to_charlist(socket_path)}, 0, [
               :binary,
               active: false
             ]),
           :ok <- :gen_tcp.send(socket, encoded),
           {:ok, line} <- recv_line(socket, "") do
        :gen_tcp.close(socket)
        decode_response(line)
      else
        {:error, reason} -> {:error, reason}
      end
    end
  end

  def default_socket_path do
    Path.join([System.user_home!(), ".agent-fabric", "agent.sock"])
  end

  def default_register_payload do
    %{
      bridgeVersion: "0.1.0",
      agent: %{
        id: "elixir-orchestrator",
        displayName: "Elixir Orchestrator",
        vendor: "agent-fabric"
      },
      host: %{name: "Agent Fabric Elixir", transport: "uds"},
      workspace: %{root: File.cwd!(), source: "cwd"},
      capabilities: %{
        roots: false,
        notifications: true,
        notificationsVisibleToAgent: %{declared: "yes", observed: "yes"},
        sampling: false,
        streamableHttp: false,
        litellmRouteable: true,
        outcomeReporting: "explicit"
      },
      notificationSelfTest: %{observed: "yes", detail: "local Elixir orchestrator"}
    }
  end

  # --- Private ---

  defp recv_line(socket, acc) do
    case :gen_tcp.recv(socket, 0, 30_000) do
      {:ok, chunk} ->
        next = acc <> chunk

        case String.split(next, "\n", parts: 2) do
          [line, _rest] -> {:ok, line}
          [_partial] -> recv_line(socket, next)
        end

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp decode_response(line) do
    with {:ok, decoded} <- Jason.decode(line) do
      decode_response_struct(decoded)
    else
      {:error, reason} -> {:error, reason}
    end
  end

  @doc false
  def decode_response_struct(%{"ok" => true, "result" => result}) do
    {:ok, result}
  end

  def decode_response_struct(%{"ok" => false, "error" => error}) do
    {:error, error}
  end

  def decode_response_struct(other) do
    {:error, {:unexpected_response, other}}
  end

  defp unique_id do
    "elixir_" <> Base.url_encode64(:crypto.strong_rand_bytes(12), padding: false)
  end
end
